"use client"
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
//export const metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const logout = ()=>{

  }
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" Crossorigin="anonymous" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" Crossorigin="anonymous"></script> 
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        { pathname !== '/' ? <nav className="navbar navbar-expand-lg bg-body-tertiary">
          <div className="container-fluid">
            <Link className="navbar-brand" href="/home">Product App</Link>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                <li className="nav-item">
                  <Link className={`nav-link ${pathname === '/home'? ' active' : ''}`}  aria-current="page" href="/home">Home</Link>
                </li>
                <li className="nav-item">
                  <Link className={`nav-link ${pathname === '/products'? ' active' : ''}`} href="/products">Products</Link>
                </li>
                <li className="nav-item">
                  <Link className={`nav-link ${pathname === '/uploadFile'? ' active' : ''}`} href="/uploadFile">Upload File</Link>
                </li>
              </ul>
                <button className="btn btn-outline-success" type="button" onClick={logout}>LogOut</button>
             
            </div>
          </div>
        </nav> :null}
        {children}
      </body>
    </html>
  );
}
